import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import { Poppins, Noto_Sans_Thai } from 'next/font/google';
import Footer from "@/components/Footer";
import IconEventXFull from "@/assets/IconEventXFull";

const poppins = Poppins({
  weight: ['300', '400', '600'],
  subsets: ['latin'],  
});

const notoSansThai = Noto_Sans_Thai({
  weight: ['400', '700'],
  subsets: ['thai'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Event X</title>
        <link rel="icon" href="/EVENTX_logo.svg" type="image/x-icon" />
      </head>
      <body className={`${poppins.className} ${notoSansThai.className}`}>
        <header className="flex px-6 items-center justify-between">
          <IconEventXFull width={160} height={80} />
          <div className="py-6">
            <Navbar />
          </div>
        </header>
        <main className="pb-16">{children}</main>
        <footer>
          <Footer />
          {/* <p>&copy; 2024 Event Platform. All rights reserved.</p> */}
        </footer>
      </body>
    </html>
  );
}
